### ISSUE TITLE
output graphics distortion

### ISSUE THREAD

**Issue by justanotherlad** [jfultz/Chatbook#8]
The graphics of my output in the notebook cells seem a little bit distorted and different from the README.md 
What can be the reason for it? ,e.g., here the `ExternalEvaluate` box does not appear, with yellow vertical lines, like bullet, for each newline.

![Screenshot from 2023-03-27 16-12-14](https://user-images.githubusercontent.com/31207633/227919831-1540065d-0116-45f1-a935-340a98d2ce9b.png)

**Comment by ConnorGray** [comment]
`ExternalEvaluate` cells are only created when ChatGPT outputs Markdown code blocks like:


    ```bash
    ...
    ```

In your example above, ChatGPT may have generated a code block like:

    ```
    ...
    ```

So the output cell created used the generic "ChatAssistantProgram" style instead of "ChatAssistantExternalLanguage".

We're hoping we can make ChatGPT's tagging of these Markdown code blocks more reliable using a better system prompt.

The yellow dashed lines are new, the screenshots in the README haven't been updated yet to reflect them. They're used to indicate cells that represent the chat assistant output. (They all have cell styles that start with "ChatAssistant".)

**Comment by rhennigan** [comment]
External languages should now be handled much better. In the latest version, you should get buttons that generate the appropriate external language cell:

![ChatbookShellCommand](https://user-images.githubusercontent.com/6674723/234031983-a80a1c2a-cc07-475c-8bf7-7c88c494aaf0.gif)

Note: there are instructions in the prompt to include the language when writing code blocks, but it sometimes fails to follow this rule. GPT-4 is much better than GPT-3.5 at adhering to this.
